# Generated by Django 2.2.1 on 2019-07-24 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190724_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='contentPath',
            field=models.ImageField(max_length=512, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='text',
            name='contentPath',
            field=models.FileField(default='/', max_length=250, upload_to='texts/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='voice',
            name='contentPath',
            field=models.FileField(default='/', max_length=512, upload_to='voices/'),
            preserve_default=False,
        ),
    ]
