# Generated by Django 2.2.1 on 2019-07-18 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_voice'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextToTextTask',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Task')),
                ('content', models.CharField(max_length=250)),
                ('answer', models.CharField(max_length=250)),
            ],
            bases=('core.task',),
        ),
        migrations.CreateModel(
            name='TextToVoiceTask',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Task')),
                ('content', models.CharField(max_length=250)),
                ('answer', models.FileField(upload_to='voices/')),
            ],
            bases=('core.task',),
        ),
        migrations.AddField(
            model_name='voice',
            name='voice',
            field=models.FileField(blank=True, null=True, upload_to='voices/'),
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VoiceToTextTask',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Task')),
                ('answer', models.CharField(max_length=250)),
                ('content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Voice')),
            ],
            bases=('core.task',),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=250)),
                ('amount', models.IntegerField(default=0)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Wallet')),
            ],
        ),
    ]
