# Generated by Django 2.2.1 on 2019-06-16 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190611_1733'),
        ('core', '0003_dataset'),
    ]

    operations = [
    ]
