# Generated by Django 2.2.1 on 2019-07-24 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190724_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='qid',
            field=models.IntegerField(default=0),
        ),
    ]
