# Generated by Django 2.2.1 on 2019-07-24 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190724_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='qid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='texttotexttask',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Text'),
        ),
        migrations.AlterField(
            model_name='texttovoicetask',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Text'),
        ),
        migrations.AlterField(
            model_name='voicetotexttask',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Voice'),
        ),
    ]
