# Generated by Django 2.2.1 on 2019-06-16 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_merge_20190616_0835'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='docfile',
            new_name='doc_file',
        ),
        migrations.AlterField(
            model_name='dataset',
            name='dataType',
            field=models.CharField(choices=[('I2T', 'Image Labeling'), ('V2T', 'Voice To Text'), ('T2T', 'Text To Text'), ('T2V', 'Text To Voice')], max_length=3),
        ),
        migrations.DeleteModel(
            name='Reputation',
        ),
    ]
