# Generated by Django 2.2.1 on 2019-07-21 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190721_1217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='contentPath',
        ),
        migrations.RenameField(
            model_name='voice',
            old_name='voice',
            new_name='contentPath',
        ),
    ]
