# Generated by Django 2.2.1 on 2019-07-21 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190721_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagelabelingtask',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Image'),
        ),
    ]
