# Generated by Django 2.2.1 on 2019-07-23 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190721_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagelabelingtask',
            name='category',
        ),
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
