# Generated by Django 2.2.1 on 2019-06-08 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_manager', '0003_auto_20190531_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_num',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
