# Generated by Django 2.2.1 on 2019-06-08 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_manager', '0004_auto_20190608_0548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='id',
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_num',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
